### ISSUE TITLE
Exclude public/assets/data from main publish tasks

### ISSUE THREAD

**Issue by critmcdonald** [statesman/tx-school-data#5]
I've yet to figure out how to exclude the `public/assets/data` directory from the main S3 publish tasks. This is related to #4.

**Comment by critmcdonald** [comment]
This is kinda shitty, but unless we figure this out, just remove `public/assests/data` folder from `public` before pushing.

**Comment by danhillreports** [comment]
Could also try to [`uploadDir`](https://github.com/andrewrk/node-s3-client#clientuploaddirparams) on specific directories instead of sync

**Comment by danhillreports** [comment]
The official aws s3 command line tool has an exclude option on its exclude function https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html

**Comment by critmcdonald** [comment]
I'm not sure how to integrate that cli into the Grunt task. On a whim I tried a adding an `exclude` param in the upload params of te deployS3.js task, but that didn't work.
